### ISSUE TITLE
UI Fixes in the New Dapp Interfaces

### ISSUE THREAD

**Issue by zaryab2000** [ethereum-push-notification-service/epns-dapp-staging#57]
- **CREATE CHANNEL** page Is not implemented adequately for the Dark Theme yet. Texts get hidden out when in dark theme (images attached below)
- Even if Channel Channel Creation fails (due to out of gas), the UI shows **CHANNEL CREATED.**

- After a successful Channel Creation, The Channel Owner, when logged in with his/her
- Address, should see his/her **CHANNEL NAME** under the **“Communicate**” section instead of “**CREATE CHANNEL**”  again.
- On the **VIEW CHANNEL** page, Search Bar is not Fixed to its position. Distorts the Channel Names when scrolled Upwards. (Search bar could be something like we have in staging old ui)
- Notification messages in dark mode aren’t very clear
- Receive Notif section links are not working. Need to assign the right URLs there.

**Comment by Aman035** [comment]
All bugs fixed
