### ISSUE TITLE
Unable to unsubscribe a channel

### ISSUE THREAD

**Issue by gufertum** [ethereum-push-notification-service/epns-dapp-staging#6]
If I try to unsubscribe, I get a 'Transaction Failed' message.
I'm logged in an connected to ropsten using metamask and have some ETH.
Subscribing works, but unsubscribe not.

Error on screen:
![image](https://user-images.githubusercontent.com/550133/130591460-2e0bf4da-8958-4ffd-8059-44b621f69906.png)

Error in console:
![image](https://user-images.githubusercontent.com/550133/130591364-065cb6d6-ba0a-4ed3-b866-a7f744b6be36.png)

**Comment by VectoTec** [comment]
Its fixed now.
